from pydantic import BaseModel, Field
from typing import List, Optional

class SourceModel(BaseModel):
    document: str = Field(..., description="The name of the source PDF document.")
    page: int = Field(..., description="The page number in the PDF (1-indexed).")
    text: Optional[str] = Field(None, description="The content of the text chunk.")
    score: Optional[float] = Field(None, description="The similarity or distance score.")

class AskResponse(BaseModel):
    answer: str = Field(..., description="The response generated by the LLM.")
    sources: List[SourceModel] = Field(default=[], description="The context source citations.")

class UploadResponse(BaseModel):
    success: bool = Field(..., description="True if the PDF was uploaded, parsed, and embedded successfully.")
    filename: str = Field(..., description="The name of the uploaded file.")
    chunks_processed: int = Field(..., description="The number of vector chunks stored in ChromaDB.")

class HealthResponse(BaseModel):
    status: str = Field(..., description="Status string (e.g. 'healthy').")

class DocumentInfo(BaseModel):
    filename: str = Field(..., description="The name of the document file.")
    chunks_count: int = Field(..., description="The number of indexed text chunks.")

class DocumentListResponse(BaseModel):
    documents: List[DocumentInfo] = Field(default=[], description="The list of currently indexed documents.")

class DeleteResponse(BaseModel):
    success: bool = Field(..., description="True if the document was deleted successfully.")
    filename: str = Field(..., description="The name of the deleted document.")
    message: str = Field(..., description="Detailed status message.")
